---

### Install FileBeat and MetricBeat on client, add basic production configs

es_install:
  - filebeat
  - metricbeat

es_elasticsearch_domain: elasticstack-server.example.com
es_kibana_domain: elasticstack-server.example.com

es_production_mode: true
es_protocol: https
es_client_monitoring: true

### Shipper configs; adds some useful metadata to exported logs/metrics

es_shipper_name: my-client
es_shipper_env: prodution
es_shipper_tags: client.example.com

### Select and configure FileBeat modules to use. See: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html

es_filebeat_modules:
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
        var.paths: ["/var/log/syslog"]

### Select and configure MetricBeat modules to use. See: https://www.elastic.co/guide/en/beats/metricbeat/index.html

es_metricbeat_modules:
  metricbeat.modules:
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
      process.include_top_n:
        by_cpu: 5
        by_memory: 5

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
        - drop_event.when.regexp:
            system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

    - module: system
      period: 15m
      metricsets:
        - uptime
