---

- name: install dependencies
  apt:
    name: "{{ es_dependencies }}"
  become: yes

- name: add apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: yes

- name: add elastic repo
  apt_repository:
    repo: "{{ es_repo }}"
    state: present
    update_cache: true
  become: yes
