---

# See: https://github.com/libre-ops/ca_keys for usage

- name: Generate CA keys
  hosts: 127.0.0.1
  connection: local

  roles:
    - role: libre_ops.ca_keys
      vars:
        cert_ca_name: CA Root
        cert_organisation: OFN
        cert_unit: Monitoring

        create_java_keystores: false
        cert_pass: "{{ es_certificate_passphrase }}"

        create_keys:
          - filename: elastic
            subject:
              - "/CN=elastic"
              - "/O={{ cert_organisation }}"
              - "/OU={{ cert_unit }}"
              - "/C={{ cert_country }}"
              - "/ST={{ cert_state }}"
              - "/L={{ cert_location }}"
          - filename: kibana
            subject:
              - "/CN=kibana"
              - "/O={{ cert_organisation }}"
              - "/OU={{ cert_unit }}"
              - "/C={{ cert_country }}"
              - "/ST={{ cert_state }}"
              - "/L={{ cert_location }}"


