---

### Install ElasticSearch and Kibana, add basic production configs

es_install:
  - elasticsearch
  - kibana

es_production_mode: true
es_protocol: https

es_elasticsearch_domain: elasticstack-server.example.com
es_kibana_domain: elasticstack-server.example.com

### Define secrets. Use Ansible Vault: https://docs.ansible.com/ansible/latest/user_guide/vault.html

es_bootstrap_password: super-secure-password

es_builtin_users:
  kibana: super-secure-password
  logstash_system: super-secure-password
  beats_system: super-secure-password
  apm_system: super-secure-password
  remote_monitoring_user: super-secure-password

es_default_admin_username: admin

es_default_admin_details:
  full_name: "Admin"
  email: admin@example.com
  password: super-secure-password
  roles: ["superuser"]
